title: "Align Partners Content Portfolio"
description: "Strategic hospitality investment insights, September-December 2025"
url: ""
baseurl: ""

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js
  - src/